audit_header: false
title: Central Florida Real Estate Video Blog with The Rodriguez Team
description: >-
  Our mission at The Rodriguez Team is to be your best resource for Central
  Florida real estate advice. Whether you are a buyer, seller, or investor, our
  team of professionals can answer any questions you might have about real
  estate. If you are looking to buy or sell a home, you can get all the
  information and the latest updates, tips, and tricks from The The Rodriguez
  Team, your professional Central Florida Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: The Rodriguez Team
  title:
  license_number:
  about_markdown: >
    Our goal is to create a business surrounded by people who truly care about
    the customers and the communities they serve. Our professional approach to
    real estate allows us to be efficient with your time and wise with your
    money. Our systems are designed to stay in front of any surprises to ensure
    a smooth transaction from contract to close, whether you are buying or
    selling.


    We want to be your Real Estate team for life! We hope you feel so great
    about our service that you are excited to tell your friends and family so we
    can continue to grow and build lasting relationships.


    We look forward to serving you.
  brand: The Rodriguez Team
  brokerage: Keller Williams Elite Partners III Realty
  market: Central Florida
  address: '1200 Oakley Seaver Dr. Suite 109 Clermont, FL 34711'
  phone: 407-519-0627
  phone_type:
  phone2:
  phone2_type:
  email: adam@rodriguezteamsells.com
  url: 'http://rodriguezteamsells.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://rodriguezteamsells.kw.com/your-home-s-value/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://rodriguezteamsells.kw.com/search/#/-28479650'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Central Florida Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'https://rodriguezteamsells.kw.com/your-home-s-value/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Central Florida Home?
    CTA_text2: Search the entire MLS for your Central Florida home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://rodriguezteamsells.kw.com/search/#/-28479650'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: true
  facebook_url:
  linkedin_url: 'https://www.linkedin.com/in/adam-g-rodriguez/'
  youtube_url:
  twitter_url: 'https://twitter.com/adamgrodriguez'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/AGRodriguezPA/'
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/central-florida-real-estate-podcast-rodriguez-team/id1479478377
podcast:
  title: Central Florida Real Estate Podcast with The Rodriguez Team
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Central
    Florida Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from The Rodriguez Team - your professional
    Central Florida Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Central Florida,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: The Rodriguez Team
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Central Florida Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
site_colors:
  brand_color: '#e65810'
  theme_color: '#00336a'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'